name: continuous-deployment-workflow

on:
  push:
    branches:
      - master
      - dev

env:
  NODE_VERSION: 14.18.1

jobs:
  publish-dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build & publish container to heroku
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME_DEV }}
          dockerfile_directory: ./
          dockerfile_name: Dockerfile
          docker_options: ${{ format('{0}{1}{2}', '--no-cache --build-arg node_version=', env.NODE_VERSION, ' --build-arg environment=development') }}
          process_type: web

  publish-prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build & publish container to heroku
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME_PROD }}
          dockerfile_directory: ./
          dockerfile_name: Dockerfile
          docker_options: ${{ format('{0}{1}{2}', '--no-cache --build-arg node_version=', env.NODE_VERSION, ' --build-arg environment=production') }}
          process_type: web